Repository boostcamp-2020/IssueTracker-08, pull requests merged in 2020-10, with the labels that each got.

#38 Feat: #37 프로젝트 초기 셋팅
  .gitignore
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/utils/query.js
  Server/app.js
  Server/bin/www
  Server/package-lock.json
  Server/package.json
  Server/public/stylesheets/style.css
  Server/routes/index.js
  Server/routes/users.js
  Server/server.txt
  Server/test/test.txt
  Server/views/error.ejs
  Server/views/index.ejs
Labels: backend, enhancement

#83 [Scene: IssueList] CollectionView 화면 업데이트
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/sue.xcuserdatad/UserInterfaceState.xcuserstate
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListRouter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
Labels: IOS

#86 Feat: #9 IssueList VIP 패턴 제작
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Extension/issue.json
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListWorker.swift
Labels: IOS

#87 CollectionView의 cell mock data로 채워 넣기
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListWorker.swift
  IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueListCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/Services/IssueDataManager.swift
  IssueTracker/IssueTracker/Scenes/Services/issue.json
Labels: IOS

#85 Feat : Milestone CRUD
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/milestone/milestone.controller.js
  Server/api/milestone/milestone.router.js
  Server/api/milestone/milestone.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/milestone.query.js
  Server/api/utils/returnForm.js
  Server/app.js
  Server/config/database.config.js
  Server/config/database.js
  Server/public/stylesheets/style.css
  Server/routes/index.js
  Server/routes/users.js
  Server/test.txt
  Server/views/error.ejs
  Server/views/index.ejs
Labels: backend

#88 Feat : #29 프로필 이미지 조회 API
  Server/api/user/user.controller.js
  Server/api/user/user.router.js
  Server/api/user/user.service.js
  Server/api/utils/user.query.js
  Server/routes/index.js
Labels: backend

#89 Feat: #18 Signin GitHub
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/app.js
  Server/config/database.config.js
  Server/config/database.js
  Server/config/github.oauth.js
  Server/package-lock.json
  Server/package.json
  Server/public/stylesheets/style.css
  Server/routes/index.js
  Server/routes/users.js
  Server/views/index.ejs
Labels: backend

#94 Issue list의 label, milestone UILabel 사이즈 문제 조정
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Extensions/UIColor+HexString.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueListCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/Services/issue.json
Labels: IOS

#92 Issue & comment 관련 API 구현
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/issue/issue.template.js
  Server/api/utils/issue.query.js
Labels: backend

#97 dev-server <- feat-issue-api merge
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/issue/issue.template.js
  Server/api/user/user.controller.js
  Server/api/user/user.router.js
  Server/api/user/user.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/user.query.js
  Server/app.js
  Server/config/database.config.js
  Server/config/database.js
  Server/public/stylesheets/style.css
  Server/routes/index.js
  Server/routes/users.js
  Server/views/error.ejs
  Server/views/index.ejs
Labels: backend

#100 Feat : #20 존재하는 유저는 imageUrl Update
  Server/api/signin/signin.service.js
  Server/api/utils/signin.query.js
Labels: backend

#101 dev-server <- signin api merge
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/signin.query.js
  Server/config/github.oauth.js
  Server/package-lock.json
  Server/package.json
  Server/routes/index.js
  Server/signin.txt
Labels: backend

#107 [dev ← dev-ios] Merge
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/gim-yeonglyeol.xcuserdatad/UserInterfaceState.xcuserstate
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/sue.xcuserdatad/UserInterfaceState.xcuserstate
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/Assets.xcassets/logo.imageset/768px-Ei-sc-github.svg.png
  IssueTracker/IssueTracker/Assets.xcassets/logo.imageset/Contents.json
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/CollectionViewController.swift
  IssueTracker/IssueTracker/Extension/issue.json
  IssueTracker/IssueTracker/Extensions/UIColor+HexString.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListRouter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListWorker.swift
  IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueListCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/Services/IssueDataManager.swift
  IssueTracker/IssueTracker/Scenes/Services/issue.json
  IssueTracker/IssueTracker/Scenes/SignIn/RootCoordinator.swift
  IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
  IssueTracker/IssueTracker/ViewController.swift
  IssueTracker/Podfile
  IssueTracker/Podfile.lock
  ios/a.txt
Labels: IOS
