Repository boostcamp-2020/IssueTracker-08, pull requests merged in 2020-11, with the labels that each got.

#109 Feat : Label CRUD & RandomColor
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/label.query.js
  Server/api/utils/returnForm.js
  Server/app.js
  Server/config/database.config.js
  Server/config/database.js
  Server/routes/index.js
  Server/routes/users.js
  Server/test.txt
  Server/views/error.ejs
  Server/views/index.ejs
Labels: backend

#112 Fix : #23 Label 조회 API 중복부분 삭제
  Server/api/label/label.controller.js
Labels: backend

#142 Issue List를 API를 사용하여 가져오기
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/Services/IssueDataManager.swift
  IssueTracker/IssueTracker/Scenes/Services/NetworkService.swift
Labels: IOS

#149 Merge : dev-server <- feat-label-api
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/utils/label.query.js
  Server/routes/index.js
Labels: 💻 backend

#148 [BE] Feat : JWT 토큰 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcodeproj/project.xcworkspace/xcuserdata/sue.xcuserdatad/UserInterfaceState.xcuserstate
  IssueTracker/IssueTracker.xcworkspace/contents.xcworkspacedata
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/Assets.xcassets/logo.imageset/768px-Ei-sc-github.svg.png
  IssueTracker/IssueTracker/Assets.xcassets/logo.imageset/Contents.json
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/CollectionViewController.swift
  IssueTracker/IssueTracker/Extension/issue.json
  IssueTracker/IssueTracker/Extensions/UIColor+HexString.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListInteractor.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListModels.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListPresenter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListRouter.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListWorker.swift
  IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueListCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/Services/IssueDataManager.swift
  IssueTracker/IssueTracker/Scenes/Services/issue.json
  IssueTracker/IssueTracker/Scenes/SignIn/RootCoordinator.swift
  IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
  IssueTracker/IssueTracker/ViewController.swift
  IssueTracker/Podfile
  IssueTracker/Podfile.lock
  README.md
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/auth.token.js
  Server/api/utils/issue.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/app.js
  Server/config/jwt.config.js
  Server/config/passport.config.js
  Server/routes/index.js
  sprint-ios.md
  sprint-web.md
Labels: 💻 backend

#150 Merge : dev-server <- feat-signin-api
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/auth.token.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/app.js
  Server/config/jwt.config.js
  Server/config/passport.config.js
  Server/routes/index.js
Labels: 💻 backend

#154 [FE] login-base-ui
  .gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/images/github.svg
  Client/src/App.scss
  Client/src/pages/login/LoginPage.jsx
  Client/src/pages/login/LoginPage.scss
  Client/src/scss/_color.scss
Labels: 🧸 frontend

#156 다중 선택 화면 구현
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTracker/Scenes/IssueList/Views/IssueListCollectionViewCell.swift
Labels: 📱 IOS

#160 Feat : #159 팝업 뷰 띄우는 방식 수정
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Scenes/LabelList/LabelCollectionViewController.swift
  IssueTracker/IssueTracker/Scenes/LabelList/LabelListRouter.swift
  IssueTracker/IssueTracker/Scenes/PopUpView/PopUpRouter.swift
  IssueTracker/IssueTracker/Scenes/PopUpView/PopUpViewController.swift
  IssueTracker/IssueTracker/Scenes/PopUpView/PopupItem.swift
Labels: 📱 IOS

#165 Merge: dev-client <- feat-login-ui
  .gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/images/github.svg
  Client/src/App.scss
  Client/src/components/oauth/github.oauth.jsx
  Client/src/components/oauth/github.oauth.scss
  Client/src/pages/login/LoginPage.jsx
  Client/src/pages/login/LoginPage.scss
  Client/src/scss/_color.scss
Labels: 🧸 frontend

#167 Feat : #159 #166 #172 레이블 생성, 수정, 삭제
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Scenes/LabelList/LabelCollectionViewController.swift
  IssueTracker/IssueTracker/Scenes/LabelList/LabelListInteractor.swift
  IssueTracker/IssueTracker/Scenes/LabelList/LabelListModels.swift
  IssueTracker/IssueTracker/Scenes/LabelList/LabelListPresenter.swift
  IssueTracker/IssueTracker/Scenes/LabelList/LabelListWorker.swift
  IssueTracker/IssueTracker/Scenes/LabelList/Views/LabelCollectionReusableView.swift
  IssueTracker/IssueTracker/Scenes/LabelList/Views/LabelCollectionViewCell.swift
  IssueTracker/IssueTracker/Scenes/PopUpView/PopUpViewController.swift
  IssueTracker/IssueTracker/Scenes/PopUpView/PopupItem.swift
  IssueTracker/IssueTracker/Services/LabelDataManager.swift
  IssueTracker/IssueTracker/Services/NetworkService.swift
Labels: 📱 IOS

#173 Feat : #129 이슈 목록 메뉴에 따른 화면 전환 및 MenuButton 컴포넌트화
  Client/public/favicon.ico
  Client/public/images/label.svg
  Client/public/images/milestone.svg
  Client/public/index.html
  Client/src/components/MenuButton.jsx
  Client/src/pages/issue/IssuePage.jsx
Labels: 🧸 frontend

#174 Refactor : #113 feat-login-ui 스타일 변경
  Client/package-lock.json
  Client/package.json
  Client/src/App.jsx
  Client/src/App.scss
  Client/src/client/Root.js
  Client/src/components/Menu.jsx
  Client/src/components/Routes.jsx
  Client/src/index.js
  Client/src/pages/LoginPage.jsx
  Client/src/pages/index.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/pages/login/LoginPage.scss
  Client/src/scss/_color.scss
  Client/src/shared/App.jsx
  Client/webpack.config.js
  README.md
Labels: 🎀 frontend

#176 Merge : dev-client <- feat-login-ui
  Client/src/pages/index.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/shared/App.jsx
  README.md
Labels: 🎀 frontend

#177 Feat : #131 이슈 내용 작성이 가능한 Form 디자인 진행
  Client/src/components/IssueForm.jsx
  Client/src/pages/issue/IssuePostPage.jsx
Labels: 🎀 frontend

#186 Fix : 로그인, 라벨 API 문제 해결
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/signin/signin.service.js
  Server/api/utils/label.query.js
  Server/api/utils/signin.query.js
Labels: 💻 backend

#183 Feat : 이슈 상세 화면 UI 구현
  Client/public/images/emoticon.svg
  Client/public/images/exclam_circle.svg
  Client/public/images/menu.svg
  Client/src/components/IssueCommentForm.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
Labels: 🎀 frontend

#187 Merge : dev-server <- feat-update-api
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/issue/issue.template.js
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/user/user.controller.js
  Server/api/user/user.router.js
  Server/api/user/user.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/label.query.js
  Server/api/utils/milestone.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/api/utils/user.query.js
  Server/app.js
  Server/package-lock.json
  Server/package.json
  Server/routes/index.js
Labels: ✨ enhancement, 💻 backend

#189 Merge : dev-client <- feat-issue-create-ui
  Client/src/components/IssueForm.jsx
  Client/src/pages/issue/IssuePostPage.jsx
Labels: 🎀 frontend

#191 Feat : #132, #134 이슈 등록 버튼 구현
  Client/src/components/IssueForm.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Client/webpack.config.js
Labels: 🎀 frontend

#190 Merge : dev-client <- feat-issue-detail-ui
  Client/public/images/emoticon.svg
  Client/public/images/exclam_circle.svg
  Client/public/images/menu.svg
  Client/src/components/IssueCommentForm.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
Labels: 🎀 frontend

#192 Merge : dev-client <- feat-issue-ui
  Client/public/favicon.ico
  Client/public/images/label.svg
  Client/public/images/milestone.svg
  Client/public/index.html
  Client/src/components/MenuButton.jsx
  Client/src/pages/issue/IssuePage.jsx
Labels: 🎀 frontend

#193 Merge : dev-client <- feat-issue-create-ui
  Client/src/components/IssueForm.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Client/webpack.config.js
Labels: 🎀 frontend

#196 Fix : #155 Swipe로 close 후 title 에러 수정
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Scenes/IssueList/IssueListViewController.swift
  IssueTracker/IssueTrackerTests/Info.plist
  IssueTracker/IssueTrackerUITests/Info.plist
Labels: 📱 IOS

#194 Dev client
  .gitignore
  Client/.babelrc
  Client/.eslintrc.js
  Client/package-lock.json
  Client/package.json
  Client/public/favicon.ico
  Client/public/images/emoticon.svg
  Client/public/images/exclam_circle.svg
  Client/public/images/github.svg
  Client/public/images/label.svg
  Client/public/images/menu.svg
  Client/public/images/milestone.svg
  Client/public/index.html
  Client/src/client/Root.js
  Client/src/components/Header.jsx
  Client/src/components/IssueCommentForm.jsx
  Client/src/components/IssueForm.jsx
  Client/src/components/MenuButton.jsx
  Client/src/components/oauth/github.oauth.jsx
  Client/src/index.js
  Client/src/pages/index.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/pages/milestone/MilestonePostPage.jsx
  Client/src/shared/App.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Client/webpack.config.js
  README.md
  sprint-ios.md
  sprint-web.md
Labels: 🎀 frontend

#188 Merge : dev <- dev-server
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/issue/issue.template.js
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/user/user.controller.js
  Server/api/user/user.router.js
  Server/api/user/user.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/label.query.js
  Server/api/utils/milestone.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/api/utils/user.query.js
  Server/app.js
  Server/package-lock.json
  Server/package.json
  Server/routes/index.js
Labels: ✨ enhancement, 💻 backend

#199 Merge : master <- dev
  .gitignore
  Client/.babelrc
  Client/.eslintrc.js
  Client/package-lock.json
  Client/package.json
  Client/public/favicon.ico
  Client/public/images/emoticon.svg
  Client/public/images/exclam_circle.svg
  Client/public/images/github.svg
  Client/public/images/label.svg
  Client/public/images/menu.svg
  Client/public/images/milestone.svg
  Client/public/index.html
  Client/src/client/Root.js
  Client/src/components/Header.jsx
  Client/src/components/IssueCommentForm.jsx
  Client/src/components/IssueForm.jsx
  Client/src/components/MenuButton.jsx
  Client/src/components/oauth/github.oauth.jsx
  Client/src/index.js
  Client/src/pages/index.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/pages/milestone/MilestonePostPage.jsx
  Client/src/shared/App.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Client/webpack.config.js
  Server/api/issue/issue.controller.js
  Server/api/issue/issue.router.js
  Server/api/issue/issue.service.js
  Server/api/issue/issue.template.js
  Server/api/label/label.controller.js
  Server/api/label/label.router.js
  Server/api/label/label.service.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/user/user.controller.js
  Server/api/user/user.router.js
  Server/api/user/user.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/label.query.js
  Server/api/utils/milestone.query.js
  Server/api/utils/returnForm.js
  Server/api/utils/signin.query.js
  Server/api/utils/user.query.js
  Server/app.js
  Server/package-lock.json
  Server/package.json
  Server/routes/index.js
Labels: 🎀 frontend, 💻 backend

#232 Feat : #6 Github OAuth 구현
  IssueTracker/IssueTracker.xcodeproj/project.pbxproj
  IssueTracker/IssueTracker.xcworkspace/xcshareddata/swiftpm/Package.resolved
  IssueTracker/IssueTracker/Base.lproj/Main.storyboard
  IssueTracker/IssueTracker/Info.plist
  IssueTracker/IssueTracker/Scenes/SignIn/SignInModel.swift
  IssueTracker/IssueTracker/Scenes/SignIn/SignInViewController.swift
  IssueTracker/IssueTracker/Services/EndPoint.swift
  IssueTracker/IssueTracker/Services/NetworkService.swift
  IssueTracker/IssueTracker/Services/OAuthGithubManager.swift
Labels: 📱 IOS

#234 Feat : 마일스톤 및 레이블 전체 틀 구축
  Client/src/components/issue/IssueCommentForm.jsx
  Client/src/components/issue/IssueForm.jsx
  Client/src/components/label/Label.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/shared/button/MenuButton.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/Container.jsx
  Client/src/components/shared/container/Header.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/ItemHeader.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/shared/App.jsx
  Client/src/utils/color.js
Labels: 🎀 frontend

#236 [FE] Feat : #114 프론트 백엔드 OAuth로그인 연동
  Client/package-lock.json
  Client/package.json
  Client/src/pages/Callback.js
  Client/src/pages/index.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/shared/App.jsx
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/app.js
  Server/config/github.oauth.js
  Server/package-lock.json
  Server/package.json
Labels: 🎀 frontend, 💻 backend

#241 Feat : #127 로그인 상태에 따른 메인 화면 변화
  Client/src/pages/Callback.js
  Client/src/router/LoginRouter.jsx
  Client/src/router/MainRouter.jsx
  Client/src/shared/App.jsx
  Client/src/stores/LoginStore.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Server/api/signin/signin.controller.js
Labels: 🎀 frontend

#243 Merge : dev-client <- feat-auth
  Client/package-lock.json
  Client/package.json
  Client/src/pages/Callback.js
  Client/src/pages/index.jsx
  Client/src/pages/login/LoginPage.jsx
  Client/src/router/LoginRouter.jsx
  Client/src/router/MainRouter.jsx
  Client/src/shared/App.jsx
  Client/src/stores/LoginStore.jsx
  Client/src/utils/api.js
  Client/src/utils/fetchOptions.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/app.js
  Server/config/github.oauth.js
  Server/package-lock.json
  Server/package.json
Labels: 🎀 frontend, 💻 backend

#256 [BE] Hotfix API 리팩토링 & apple 로그인 기능 추가
  Client/src/pages/Callback.js
  Server/api/issue/issue.router.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/issue.query.js
Labels: 💻 backend

#259 Feat : useContext와 useReducer를 이용한 Label 목록 관리
  Client/package.json
  Client/src/components/label/Label.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelList.jsx
  Client/src/components/label/LabelTitle.jsx
  Client/src/hooks/useFetch.js
  Client/src/pages/label/LabelPage.jsx
  Client/src/reducers/labelReducer.js
  Client/src/stores/LabelStore.js
  Client/src/utils/api.js
Labels: 🎀 frontend

#260 Feat : #133 이슈 디테일 페이지
  Client/public/images/close.svg
  Client/src/components/issue/IssueCommentForm.jsx
  Client/src/components/issue/IssueForm.jsx
  Client/src/components/issue/IssueStateButton.jsx
  Client/src/components/label/Label.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/shared/button/MenuButton.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/Container.jsx
  Client/src/components/shared/container/Header.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/ItemHeader.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/shared/App.jsx
  Client/src/utils/api.js
  Client/src/utils/color.js
  Client/src/utils/getDiffTime.js
Labels: 🎀 frontend

#263 Merge : dev-client <- feat-issue-detail
  Client/public/images/close.svg
  Client/src/components/issue/IssueStateButton.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/utils/api.js
Labels: 🎀 frontend

#261 Merge : dev <- feat-label-milestone-ui
  Client/package.json
  Client/src/components/Header.jsx
  Client/src/components/label/Label.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelList.jsx
  Client/src/components/label/LabelTitle.jsx
  Client/src/hooks/useFetch.js
  Client/src/pages/label/LabelPage.jsx
  Client/src/reducers/labelReducer.js
  Client/src/stores/LabelStore.js
  Client/src/utils/api.js
Labels: 🎀 frontend

#268 Feat : Label 추가, 수정 기능 구현
  Client/public/images/reload.svg
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelForm.jsx
  Client/src/components/label/LabelMenu.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/reducers/labelReducer.js
  Client/src/stores/LabelStore.js
  Client/src/stores/LoginStore.jsx
  Client/src/utils/api.js
  Client/src/utils/color.js
  Client/src/utils/fetchOptions.js
Labels: 🎀 frontend

#269 Feat : Issue List 동적 기능 추가
  Client/src/components/issue/main/issueList.jsx
  Client/src/components/issue/main/issueListHeader.jsx
  Client/src/components/issue/main/issueMain.jsx
  Client/src/pages/issue/IssuePage.jsx
  Client/src/reducers/issueReducer.js
  Client/src/reducers/userReducer.js
  Client/src/stores/IssueStore.js
  Client/src/stores/UserStore.js
  Client/src/utils/api.js
Labels: 🎀 frontend

#271 Merge : dev-client <- feat-label-ui
  Client/public/images/reload.svg
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelForm.jsx
  Client/src/components/label/LabelMenu.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/reducers/labelReducer.js
  Client/src/stores/LabelStore.js
  Client/src/stores/LoginStore.jsx
  Client/src/utils/api.js
  Client/src/utils/color.js
  Client/src/utils/fetchOptions.js
Labels: 🎀 frontend

#270 Feat : issue-detail-ui
  Client/public/images/red_close.svg
  Client/src/components/issue/IssueCommentForm.jsx
  Client/src/components/issue/IssueComments.jsx
  Client/src/pages/Callback.js
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/utils/api.js
  Server/api/issue/issue.router.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/issue.query.js
Labels: 🎀 frontend

#284 Feat : #266 Create IssueComment & Close issue & Reopen Issue
  Client/public/images/reload.svg
  Client/src/components/comment/CommentContainer.jsx
  Client/src/components/comment/CommentForm.jsx
  Client/src/components/comment/CommentNumber.jsx
  Client/src/components/comment/Comments.jsx
  Client/src/components/issue/IssueCloseButton.jsx
  Client/src/components/issue/IssueComments.jsx
  Client/src/components/issue/IssueEdit.jsx
  Client/src/components/issue/IssueForm.jsx
  Client/src/components/issue/IssueStateButton.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelForm.jsx
  Client/src/components/label/LabelMenu.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/hooks/useFetch.js
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/reducers/commentReducer.js
  Client/src/reducers/issueDetailReducer.js
  Client/src/reducers/labelReducer.js
  Client/src/stores/CommentStore.jsx
  Client/src/stores/IssueDetailStore.jsx
  Client/src/stores/LabelStore.js
  Client/src/stores/LoginStore.jsx
  Client/src/utils/api.js
  Client/src/utils/color.js
  Client/src/utils/fetchOptions.js
  Server/api/issue/issue.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/user.query.js
Labels: 🎀 frontend

#279 Feat : Milestone 생성, 수정, 삭제
  Client/src/components/issue/main/issueListTemplate.jsx
  Client/src/components/milestone/MilestoneContainer.jsx
  Client/src/components/milestone/MilestoneForm.jsx
  Client/src/components/milestone/MilestoneHeaderMenu.jsx
  Client/src/components/milestone/MilestoneList.jsx
  Client/src/components/milestone/MilestonePostHeader.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/index.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/milestone/MilestoneEditPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/pages/milestone/MilestonePostPage.jsx
  Client/src/reducers/milestoneReducer.js
  Client/src/router/MainRouter.jsx
  Client/src/shared/App.jsx
  Client/src/stores/LabelStore.jsx
  Client/src/stores/MilestoneStore.jsx
  Client/src/utils/api.js
  Client/src/utils/getDiffTime.js
  Client/src/utils/number.js
  Client/src/utils/time.js
Labels: 🎀 frontend

#283 Feat : Issue 필터링 기능 & 체크박스를 통한 일괄 Issue 상태 변경
  Client/public/images/reload.svg
  Client/src/components/issue/main/button/assigneeDropdown.jsx
  Client/src/components/issue/main/button/authorDropdown.jsx
  Client/src/components/issue/main/button/closedHeaderBtn.jsx
  Client/src/components/issue/main/button/filterDropdown.jsx
  Client/src/components/issue/main/button/labelDropdown.jsx
  Client/src/components/issue/main/button/milestoneDropdown.jsx
  Client/src/components/issue/main/button/openHeaderBtn.jsx
  Client/src/components/issue/main/issueList.jsx
  Client/src/components/issue/main/issueListHeader.jsx
  Client/src/components/issue/main/issueListTemplate.jsx
  Client/src/components/label/LabelContainer.jsx
  Client/src/components/label/LabelForm.jsx
  Client/src/components/label/LabelMenu.jsx
  Client/src/components/shared/button/NewButton.jsx
  Client/src/components/shared/container/ItemContainer.jsx
  Client/src/components/shared/container/Menu.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/Callback.js
  Client/src/pages/issue/IssuePage.jsx
  Client/src/pages/issue/button/LabelBtn.jsx
  Client/src/pages/issue/button/MilestoneBtn.jsx
  Client/src/pages/label/LabelPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/reducers/checkReducer.js
  Client/src/reducers/issueReducer.js
  Client/src/reducers/labelReducer.js
  Client/src/stores/IssueStore.jsx
  Client/src/stores/LabelStore.js
  Client/src/stores/LoginStore.jsx
  Client/src/stores/UserStore.jsx
  Client/src/utils/api.js
  Client/src/utils/color.js
  Client/src/utils/fetchOptions.js
  Server/api/issue/issue.router.js
  Server/api/signin/signin.controller.js
  Server/api/signin/signin.router.js
  Server/api/signin/signin.service.js
  Server/api/utils/issue.query.js
Labels: 🎀 frontend

#286 Merge : dev-client <- feat-issue-detail
  Client/public/images/red_close.svg
  Client/src/components/comment/CommentContainer.jsx
  Client/src/components/comment/CommentForm.jsx
  Client/src/components/comment/CommentNumber.jsx
  Client/src/components/comment/Comments.jsx
  Client/src/components/issue/IssueCloseButton.jsx
  Client/src/components/issue/IssueCommentForm.jsx
  Client/src/components/issue/IssueEdit.jsx
  Client/src/components/issue/IssueStateButton.jsx
  Client/src/hooks/useFetch.js
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/issue/IssuePostPage.jsx
  Client/src/reducers/commentReducer.js
  Client/src/reducers/issueDetailReducer.js
  Client/src/stores/CommentStore.jsx
  Client/src/stores/IssueDetailStore.jsx
  Client/src/utils/api.js
  Server/api/issue/issue.service.js
  Server/api/utils/issue.query.js
  Server/api/utils/user.query.js
Labels: 🎀 frontend

#287 Merge : dev-client <- feat-milestone-ui
  Client/src/components/issue/main/issueListTemplate.jsx
  Client/src/components/milestone/MilestoneContainer.jsx
  Client/src/components/milestone/MilestoneForm.jsx
  Client/src/components/milestone/MilestoneHeaderMenu.jsx
  Client/src/components/milestone/MilestoneList.jsx
  Client/src/components/milestone/MilestonePostHeader.jsx
  Client/src/components/shared/text/Title.jsx
  Client/src/pages/index.jsx
  Client/src/pages/issue/IssueDetailPage.jsx
  Client/src/pages/milestone/MilestoneEditPage.jsx
  Client/src/pages/milestone/MilestonePage.jsx
  Client/src/pages/milestone/MilestonePostPage.jsx
  Client/src/reducers/milestoneReducer.js
  Client/src/router/MainRouter.jsx
  Client/src/shared/App.jsx
  Client/src/stores/LabelStore.jsx
  Client/src/stores/MilestoneStore.jsx
  Client/src/utils/api.js
  Client/src/utils/getDiffTime.js
  Client/src/utils/number.js
  Client/src/utils/time.js
Labels: 🎀 frontend
